### ISSUE TITLE
SIGSEGV when executing playbook with playbook-action and DATABASE="false"

### ISSUE THREAD

**Issue by antonatos** [COSSAS/SOARCA#256]
How to reproduce:

1. Start a SOARCA instance with DATABASE="false" configured
2. Execute a playbook via the POST /playbook API that contains a playbook-action step. A sample playbook is attached
3. A SIGSEGV happens on the following line (https://github.com/COSSAS/SOARCA/blob/e8eb6b68ad55f46a510c3103154dd546195374f3/internal/executors/playbook_action/playbook_action.go#L57)

playbook, err := playbookRepo.Read(step.PlaybookID)

the error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8bdb02]
[playbook_action_test.json](https://github.com/user-attachments/files/17803521/playbook_action_test.json)

What is expected:
An error to be thrown to gracefully notify the user that the playbook cannot be retrieved

**Comment by MaartendeKruijf** [comment]
Unfortunately we could not reproduce this. If it happens again we will further investigate.
