### ISSUE TITLE
Validation with CACAO json schemas cds03

### ISSUE THREAD

**Issue by lucamrgs** [COSSAS/SOARCA#40]
Currently the CACAO schema validation is performed at schemas at models/validators/schema.go, with the CACAO V2 draft 1. The most up to date is the CACAO V2 draft 3, at: "https://raw.githubusercontent.com/cyentific-rni/cacao-json-schemas/cacao-v2.0-csd03/schemas/playbook.json".

This feature request is to change the schema validation from CACAO V2 draft 1, to CACAO V2 draft 3

**Comment by hidde-jan** [comment]
FYI, the roaster maintainers also maintain schema's based on the latest spec: https://github.com/opencybersecurityalliance/cacao-roaster/tree/main/lib/cacao-json-schemas/schemas

Maybe they could be helpful at some point.

**Comment by lucamrgs** [comment]
Aah yes indeed, good one. We should use those actually

**Comment by lucamrgs** [comment]
Actually to add to this, I remember now that there is yet another repo that should contain the maintained official cacao schemas from the cacao TC: https://github.com/oasis-open/cacao-json-schemas/tree/main/schemas

**Comment by lucamrgs** [comment]
But those in OCA have a more recent edit
